### ISSUE TITLE
cuda OOM errors on CIFAR

### ISSUE THREAD

**Issue by jacobdineen** [jacobdineen/adv_rl#29]
```
Traceback (most recent call last):
  File "/home/jdineen/Documents/adv_rl/src/train.py", line 213, in <module>
    model.learn(
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 308, in 
learn
    return super().learn(
  File 
"/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line
281, in learn
    self.train()
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 275, in 
train
    self.policy.optimizer.step()
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in 
_use_grad
    ret = func(self, *args, **kwargs)
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/torch/optim/adam.py", line 163, in step
    adam(
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/torch/optim/adam.py", line 311, in adam
    func(params,
  File "/home/jdineen/miniconda3/envs/adv_rl1/lib/python3.10/site-packages/torch/optim/adam.py", line 565, in 
_multi_tensor_adam
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 614.00 MiB. GPU 0 has a total capacty of 23.69 GiB of 
which 396.00 MiB is free. Including non-PyTorch memory, this process has 21.43 GiB memory in use. Of the allocated memory 
20.52 GiB is allocated by PyTorch, and 620.02 MiB is reserved by PyTorch but unallocated. If reserved but unallocated 
memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF
```

**Comment by jacobdineen** [comment]
#31 Did some things to try to address this. May need to have a smaller resnet model
